services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crud_db
    ports:
      - "8237:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - appnet

  app:
    build: 
      context: ./backend
    image: vivii02/trabalhovollovivi:latest
    ports:
      - "8236:3000"
    environment:
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=crud_db
      - PGPORT=5432
      - PGHOST=db
    depends_on:
      - db
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
